DROP TABLE IF EXISTS Endereco;

CREATE TABLE Endereco (
    user_id     INTEGER       PRIMARY KEY AUTOINCREMENT NOT NULL,
    rua   VARCHAR (255) NOT NULL,
    cidade   VARCHAR (255) NOT NULL
);
    INSERT INTO Endereco (rua,cidade) VALUES ('linhaE', 'Espigao');
INSERT INTO Endereco (rua,cidade) VALUES ('linhaE', 'Espigao');
INSERT INTO Endereco (rua,cidade) VALUES ('linhaE', 'Espigao');
INSERT INTO Endereco (rua,cidade) VALUES ('linhaE', 'Espigao');
INSERT INTO Endereco (rua,cidade) VALUES ('linhaE', 'Espigao');
INSERT INTO Endereco (rua,cidade) VALUES ('linhaE', 'Espigao');

INSERT INTO Endereco (rua,cidade) VALUES ("P.O. Box 381, 2414 Non Av.","Raj Nandgaon");
INSERT INTO Endereco (rua,cidade) VALUES ("7695 Imperdiet Av.","Tofield");
INSERT INTO Endereco (rua,cidade) VALUES ("P.O. Box 836, 4961 Lorem, St.","Boryeong");
INSERT INTO Endereco (rua,cidade) VALUES ("Ap #755-8243 Proin St.","Slijpe");
INSERT INTO Endereco (rua,cidade) VALUES ("3591 Justo Av.","Lourdes");
INSERT INTO Endereco (rua,cidade) VALUES ("Ap #151-1760 Lectus Road","Atlanta");
INSERT INTO Endereco (rua,cidade) VALUES ("P.O. Box 568, 5395 Ullamcorper St.","Solihull");
INSERT INTO Endereco (rua,cidade) VALUES ("P.O. Box 456, 1172 Id Street","Ciplet");
INSERT INTO Endereco (rua,cidade) VALUES ("Ap #316-1149 Lorem, Rd.","Langenhagen");
INSERT INTO Endereco (rua,cidade) VALUES ("Ap #888-3255 Nullam St.","Lossiemouth");
INSERT INTO Endereco (rua,cidade) VALUES ("8472 In Street","Ulm");
INSERT INTO Endereco (rua,cidade) VALUES ("9571 Cursus Road","Weymouth");
INSERT INTO Endereco (rua,cidade) VALUES ("8410 Sit St.","Chiniot");
INSERT INTO Endereco (rua,cidade) VALUES ("Ap #834-2773 In, Ave","Neuville");
INSERT INTO Endereco (rua,cidade) VALUES ("Ap #884-392 Urna Street","Kawartha Lakes");
INSERT INTO Endereco (rua,cidade) VALUES ("Ap #424-5156 Dignissim. Street","Natales");
INSERT INTO Endereco (rua,cidade) VALUES ("7627 Lectus St.","Solingen");
INSERT INTO Endereco (rua,cidade) VALUES ("P.O. Box 927, 9732 Nunc St.","Penzance");
INSERT INTO Endereco (rua,cidade) VALUES ("Ap #642-9581 Vel Avenue","Laives/Leifers");
INSERT INTO Endereco (rua,cidade) VALUES ("P.O. Box 513, 6707 Nisl Av.","Balvano");
INSERT INTO Endereco (rua,cidade) VALUES ("P.O. Box 833, 6099 Ligula. St.","Abbeville");
INSERT INTO Endereco (rua,cidade) VALUES ("1913 Integer Avenue","Roubaix");
INSERT INTO Endereco (rua,cidade) VALUES ("5709 Urna Rd.","Innsbruck");
INSERT INTO Endereco (rua,cidade) VALUES ("331-874 Vel Rd.","San Vicente");
INSERT INTO Endereco (rua,cidade) VALUES ("276-7414 Consequat Ave","Minneapolis");
INSERT INTO Endereco (rua,cidade) VALUES ("P.O. Box 192, 9305 Proin Ave","Tuscaloosa");
INSERT INTO Endereco (rua,cidade) VALUES ("2146 Eu Rd.","Brussel X-Luchthaven Remailing");
INSERT INTO Endereco (rua,cidade) VALUES ("Ap #907-7166 Bibendum Rd.","Portobuffolè");
INSERT INTO Endereco (rua,cidade) VALUES ("P.O. Box 693, 5817 Et Ave","Wolfsburg");
INSERT INTO Endereco (rua,cidade) VALUES ("Ap #873-9811 Lobortis Rd.","Scena/Schenna");
INSERT INTO Endereco (rua,cidade) VALUES ("454-9355 Urna Road","Nieuwenrode");
INSERT INTO Endereco (rua,cidade) VALUES ("454-6353 Mollis Avenue","Codó");
INSERT INTO Endereco (rua,cidade) VALUES ("8952 Molestie Rd.","Wrigley");
INSERT INTO Endereco (rua,cidade) VALUES ("419-827 Mi Ave","La Florida");
INSERT INTO Endereco (rua,cidade) VALUES ("P.O. Box 694, 4073 Placerat Road","Meerut Cantonment");
INSERT INTO Endereco (rua,cidade) VALUES ("517-4710 Lorem, Av.","Eberswalde-Finow");
INSERT INTO Endereco (rua,cidade) VALUES ("401-2749 Sed St.","Maransart");
INSERT INTO Endereco (rua,cidade) VALUES ("889-6301 Blandit Avenue","Senftenberg");
INSERT INTO Endereco (rua,cidade) VALUES ("Ap #423-4607 Euismod St.","Pironchamps");
INSERT INTO Endereco (rua,cidade) VALUES ("3637 Dignissim Av.","Novy Oskol");
INSERT INTO Endereco (rua,cidade) VALUES ("519-7383 Magna. Ave","Ełk");
INSERT INTO Endereco (rua,cidade) VALUES ("582-6190 Ac Road","Romeral");
INSERT INTO Endereco (rua,cidade) VALUES ("Ap #617-8301 Aliquam Rd.","Worcester");
INSERT INTO Endereco (rua,cidade) VALUES ("Ap #339-6942 At St.","Parchim	City");
INSERT INTO Endereco (rua,cidade) VALUES ("P.O. Box 319, 5919 Dictum Rd.","Haverhill");
INSERT INTO Endereco (rua,cidade) VALUES ("P.O. Box 526, 5687 Cursus St.","Volokolamsk");
INSERT INTO Endereco (rua,cidade) VALUES ("3272 Dictum St.","Gibbons");
INSERT INTO Endereco (rua,cidade) VALUES ("P.O. Box 895, 4441 Lobortis St.","La Tebaida");
INSERT INTO Endereco (rua,cidade) VALUES ("P.O. Box 151, 2691 Lobortis Av.","Tarrasa");
INSERT INTO Endereco (rua,cidade) VALUES ("Ap #974-7857 Ut, Av.","Birmingham");
INSERT INTO Endereco (rua,cidade) VALUES ("4406 Dui, Rd.","Lewiston");
INSERT INTO Endereco (rua,cidade) VALUES ("Ap #958-2150 Convallis Road","Peutie");
INSERT INTO Endereco (rua,cidade) VALUES ("Ap #192-4109 Ante Street","Ballarat");
INSERT INTO Endereco (rua,cidade) VALUES ("Ap #833-9458 Mauris St.","Madurai");
INSERT INTO Endereco (rua,cidade) VALUES ("P.O. Box 413, 8053 Nisi Street","Nedlands");
INSERT INTO Endereco (rua,cidade) VALUES ("3811 Vestibulum Street","Rathenow");
INSERT INTO Endereco (rua,cidade) VALUES ("972-4357 Ut Street","Puerto Octay");
INSERT INTO Endereco (rua,cidade) VALUES ("P.O. Box 976, 8487 Lacinia Street","Leke");
INSERT INTO Endereco (rua,cidade) VALUES ("850-9604 Molestie Rd.","Corswarem");
INSERT INTO Endereco (rua,cidade) VALUES ("Ap #600-1102 Augue. Avenue","Sydney");
INSERT INTO Endereco (rua,cidade) VALUES ("555-5420 Consectetuer, Rd.","Freire");
INSERT INTO Endereco (rua,cidade) VALUES ("Ap #915-7987 Duis Av.","New Plymouth");
INSERT INTO Endereco (rua,cidade) VALUES ("738-5887 Mauris. Rd.","Jackson");
INSERT INTO Endereco (rua,cidade) VALUES ("2666 Nascetur St.","Acireale");
INSERT INTO Endereco (rua,cidade) VALUES ("802-3815 Odio St.","Sedgewick");
INSERT INTO Endereco (rua,cidade) VALUES ("P.O. Box 800, 6088 A Rd.","Reus");
INSERT INTO Endereco (rua,cidade) VALUES ("Ap #931-4980 A Rd.","Rankweil");
INSERT INTO Endereco (rua,cidade) VALUES ("Ap #298-9725 Eu, St.","Vaughan");
INSERT INTO Endereco (rua,cidade) VALUES ("P.O. Box 659, 3643 Proin Rd.","Bolano");
INSERT INTO Endereco (rua,cidade) VALUES ("654-6842 Mi. Street","Serralunga d'Alba");
INSERT INTO Endereco (rua,cidade) VALUES ("4079 Ante Rd.","Mechelen-aan-de-Maas");
INSERT INTO Endereco (rua,cidade) VALUES ("Ap #111-2235 Magna. St.","Mahbubnagar");
INSERT INTO Endereco (rua,cidade) VALUES ("8502 Elit, Av.","Pichilemu");
INSERT INTO Endereco (rua,cidade) VALUES ("Ap #583-6711 Sed St.","Orbais");
INSERT INTO Endereco (rua,cidade) VALUES ("778-8428 Nunc St.","Mayerthorpe");
INSERT INTO Endereco (rua,cidade) VALUES ("6381 Dictum. St.","Bearberry");
INSERT INTO Endereco (rua,cidade) VALUES ("203-4790 Vivamus St.","Mariquina");
INSERT INTO Endereco (rua,cidade) VALUES ("Ap #745-1189 Sagittis Avenue","Yuryuzan");
INSERT INTO Endereco (rua,cidade) VALUES ("139-5885 Curabitur St.","Meridian");
INSERT INTO Endereco (rua,cidade) VALUES ("210-3199 Iaculis St.","Tregaron");
INSERT INTO Endereco (rua,cidade) VALUES ("Ap #237-4274 Dui Avenue","Maizeret");
INSERT INTO Endereco (rua,cidade) VALUES ("Ap #363-8024 Mauris Ave","Spijkenisse");
INSERT INTO Endereco (rua,cidade) VALUES ("P.O. Box 856, 1872 Risus Av.","Borås");
INSERT INTO Endereco (rua,cidade) VALUES ("Ap #115-5740 Luctus Ave","Genk");
INSERT INTO Endereco (rua,cidade) VALUES ("Ap #797-3834 Ut St.","Grayvoron");
INSERT INTO Endereco (rua,cidade) VALUES ("460-4588 Vulputate, St.","La Baie");
INSERT INTO Endereco (rua,cidade) VALUES ("608-2230 Pede, Rd.","Craco");
INSERT INTO Endereco (rua,cidade) VALUES ("Ap #661-5004 Diam. Avenue","La Dorada");
INSERT INTO Endereco (rua,cidade) VALUES ("921-2911 Justo St.","s Herenelderen");
INSERT INTO Endereco (rua,cidade) VALUES ("5715 Pellentesque Rd.","Peñalolén");
INSERT INTO Endereco (rua,cidade) VALUES ("4982 Integer Av.","Massimino");
INSERT INTO Endereco (rua,cidade) VALUES ("P.O. Box 101, 4978 Tortor Av.","Borgone Susa");
INSERT INTO Endereco (rua,cidade) VALUES ("8237 Risus. Ave","Tresigallo");
INSERT INTO Endereco (rua,cidade) VALUES ("P.O. Box 287, 1075 Vitae Ave","Losino-Petrovsky");
INSERT INTO Endereco (rua,cidade) VALUES ("P.O. Box 950, 1726 Et, St.","Zandhoven");
INSERT INTO Endereco (rua,cidade) VALUES ("517-5469 Dictum Av.","Sint-Gillis");
INSERT INTO Endereco (rua,cidade) VALUES ("7066 Convallis Street","Rijkevorsel");
INSERT INTO Endereco (rua,cidade) VALUES ("P.O. Box 873, 3169 Duis Rd.","Mogliano");
INSERT INTO Endereco (rua,cidade) VALUES ("1654 Dui. St.","Namur");
INSERT INTO Endereco (rua,cidade) VALUES ("970 Aenean Rd.","Newark");
